// Generated by gencpp from file uav_server/ModeResponse.msg
// DO NOT EDIT!


#ifndef UAV_SERVER_MESSAGE_MODERESPONSE_H
#define UAV_SERVER_MESSAGE_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_server
{
template <class ContainerAllocator>
struct ModeResponse_
{
  typedef ModeResponse_<ContainerAllocator> Type;

  ModeResponse_()
    : feedback(0)  {
    }
  ModeResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::uav_server::ModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_server::ModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeResponse_

typedef ::uav_server::ModeResponse_<std::allocator<void> > ModeResponse;

typedef boost::shared_ptr< ::uav_server::ModeResponse > ModeResponsePtr;
typedef boost::shared_ptr< ::uav_server::ModeResponse const> ModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_server::ModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_server::ModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_server::ModeResponse_<ContainerAllocator1> & lhs, const ::uav_server::ModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_server::ModeResponse_<ContainerAllocator1> & lhs, const ::uav_server::ModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::ModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::ModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::ModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::ModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::ModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::ModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_server::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ceb5b32ea3af22073ede4a0328249e";
  }

  static const char* value(const ::uav_server::ModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ceb5b32ea3af22ULL;
  static const uint64_t static_value2 = 0x073ede4a0328249eULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_server::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_server/ModeResponse";
  }

  static const char* value(const ::uav_server::ModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_server::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 feedback\n"
"\n"
;
  }

  static const char* value(const ::uav_server::ModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_server::ModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_server::ModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_server::ModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_SERVER_MESSAGE_MODERESPONSE_H
