// Generated by gencpp from file uav_server/TopicMove.msg
// DO NOT EDIT!


#ifndef UAV_SERVER_MESSAGE_TOPICMOVE_H
#define UAV_SERVER_MESSAGE_TOPICMOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_server
{
template <class ContainerAllocator>
struct TopicMove_
{
  typedef TopicMove_<ContainerAllocator> Type;

  TopicMove_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  TopicMove_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::uav_server::TopicMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_server::TopicMove_<ContainerAllocator> const> ConstPtr;

}; // struct TopicMove_

typedef ::uav_server::TopicMove_<std::allocator<void> > TopicMove;

typedef boost::shared_ptr< ::uav_server::TopicMove > TopicMovePtr;
typedef boost::shared_ptr< ::uav_server::TopicMove const> TopicMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_server::TopicMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_server::TopicMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_server::TopicMove_<ContainerAllocator1> & lhs, const ::uav_server::TopicMove_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_server::TopicMove_<ContainerAllocator1> & lhs, const ::uav_server::TopicMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::TopicMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::TopicMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::TopicMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::TopicMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::TopicMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::TopicMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_server::TopicMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d0ade995d52d04cae303675aa442a7";
  }

  static const char* value(const ::uav_server::TopicMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d0ade995d52d04ULL;
  static const uint64_t static_value2 = 0xcae303675aa442a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_server::TopicMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_server/TopicMove";
  }

  static const char* value(const ::uav_server::TopicMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_server::TopicMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::uav_server::TopicMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_server::TopicMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopicMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_server::TopicMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_server::TopicMove_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_SERVER_MESSAGE_TOPICMOVE_H
