// Generated by gencpp from file uav_server/UavGestureResponse.msg
// DO NOT EDIT!


#ifndef UAV_SERVER_MESSAGE_UAVGESTURERESPONSE_H
#define UAV_SERVER_MESSAGE_UAVGESTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_server
{
template <class ContainerAllocator>
struct UavGestureResponse_
{
  typedef UavGestureResponse_<ContainerAllocator> Type;

  UavGestureResponse_()
    : feedback(0)  {
    }
  UavGestureResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::uav_server::UavGestureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_server::UavGestureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UavGestureResponse_

typedef ::uav_server::UavGestureResponse_<std::allocator<void> > UavGestureResponse;

typedef boost::shared_ptr< ::uav_server::UavGestureResponse > UavGestureResponsePtr;
typedef boost::shared_ptr< ::uav_server::UavGestureResponse const> UavGestureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_server::UavGestureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_server::UavGestureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_server::UavGestureResponse_<ContainerAllocator1> & lhs, const ::uav_server::UavGestureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_server::UavGestureResponse_<ContainerAllocator1> & lhs, const ::uav_server::UavGestureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::UavGestureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_server::UavGestureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::UavGestureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_server::UavGestureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::UavGestureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_server::UavGestureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_server::UavGestureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c99621d1dee505388e972db86733bb8";
  }

  static const char* value(const ::uav_server::UavGestureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c99621d1dee5053ULL;
  static const uint64_t static_value2 = 0x88e972db86733bb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_server::UavGestureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_server/UavGestureResponse";
  }

  static const char* value(const ::uav_server::UavGestureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_server::UavGestureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 feedback\n"
;
  }

  static const char* value(const ::uav_server::UavGestureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_server::UavGestureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UavGestureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_server::UavGestureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_server::UavGestureResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_SERVER_MESSAGE_UAVGESTURERESPONSE_H
