(cl:defpackage uav_client-srv
  (:use )
  (:export
   "MODESRVS"
   "<MODESRVS-REQUEST>"
   "MODESRVS-REQUEST"
   "<MODESRVS-RESPONSE>"
   "MODESRVS-RESPONSE"
   "MOVESRVS"
   "<MOVESRVS-REQUEST>"
   "MOVESRVS-REQUEST"
   "<MOVESRVS-RESPONSE>"
   "MOVESRVS-RESPONSE"
   "UAVSRVS"
   "<UAVSRVS-REQUEST>"
   "UAVSRVS-REQUEST"
   "<UAVSRVS-RESPONSE>"
   "UAVSRVS-RESPONSE"
  ))

