// Generated by gencpp from file uav_client/Mode.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_MODE_H
#define UAV_CLIENT_MESSAGE_MODE_H

#include <ros/service_traits.h>


#include <uav_client/ModeRequest.h>
#include <uav_client/ModeResponse.h>


namespace uav_client
{

struct Mode
{

typedef ModeRequest Request;
typedef ModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mode
} // namespace uav_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_client::Mode > {
  static const char* value()
  {
    return "4e20b2f68ee6c802f503418ca4f6f6af";
  }

  static const char* value(const ::uav_client::Mode&) { return value(); }
};

template<>
struct DataType< ::uav_client::Mode > {
  static const char* value()
  {
    return "uav_client/Mode";
  }

  static const char* value(const ::uav_client::Mode&) { return value(); }
};


// service_traits::MD5Sum< ::uav_client::ModeRequest> should match
// service_traits::MD5Sum< ::uav_client::Mode >
template<>
struct MD5Sum< ::uav_client::ModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::Mode >::value();
  }
  static const char* value(const ::uav_client::ModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::ModeRequest> should match
// service_traits::DataType< ::uav_client::Mode >
template<>
struct DataType< ::uav_client::ModeRequest>
{
  static const char* value()
  {
    return DataType< ::uav_client::Mode >::value();
  }
  static const char* value(const ::uav_client::ModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_client::ModeResponse> should match
// service_traits::MD5Sum< ::uav_client::Mode >
template<>
struct MD5Sum< ::uav_client::ModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::Mode >::value();
  }
  static const char* value(const ::uav_client::ModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::ModeResponse> should match
// service_traits::DataType< ::uav_client::Mode >
template<>
struct DataType< ::uav_client::ModeResponse>
{
  static const char* value()
  {
    return DataType< ::uav_client::Mode >::value();
  }
  static const char* value(const ::uav_client::ModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_MODE_H
