// Generated by gencpp from file uav_client/ModeSrvs.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_MODESRVS_H
#define UAV_CLIENT_MESSAGE_MODESRVS_H

#include <ros/service_traits.h>


#include <uav_client/ModeSrvsRequest.h>
#include <uav_client/ModeSrvsResponse.h>


namespace uav_client
{

struct ModeSrvs
{

typedef ModeSrvsRequest Request;
typedef ModeSrvsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModeSrvs
} // namespace uav_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_client::ModeSrvs > {
  static const char* value()
  {
    return "4e20b2f68ee6c802f503418ca4f6f6af";
  }

  static const char* value(const ::uav_client::ModeSrvs&) { return value(); }
};

template<>
struct DataType< ::uav_client::ModeSrvs > {
  static const char* value()
  {
    return "uav_client/ModeSrvs";
  }

  static const char* value(const ::uav_client::ModeSrvs&) { return value(); }
};


// service_traits::MD5Sum< ::uav_client::ModeSrvsRequest> should match
// service_traits::MD5Sum< ::uav_client::ModeSrvs >
template<>
struct MD5Sum< ::uav_client::ModeSrvsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::ModeSrvs >::value();
  }
  static const char* value(const ::uav_client::ModeSrvsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::ModeSrvsRequest> should match
// service_traits::DataType< ::uav_client::ModeSrvs >
template<>
struct DataType< ::uav_client::ModeSrvsRequest>
{
  static const char* value()
  {
    return DataType< ::uav_client::ModeSrvs >::value();
  }
  static const char* value(const ::uav_client::ModeSrvsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_client::ModeSrvsResponse> should match
// service_traits::MD5Sum< ::uav_client::ModeSrvs >
template<>
struct MD5Sum< ::uav_client::ModeSrvsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::ModeSrvs >::value();
  }
  static const char* value(const ::uav_client::ModeSrvsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::ModeSrvsResponse> should match
// service_traits::DataType< ::uav_client::ModeSrvs >
template<>
struct DataType< ::uav_client::ModeSrvsResponse>
{
  static const char* value()
  {
    return DataType< ::uav_client::ModeSrvs >::value();
  }
  static const char* value(const ::uav_client::ModeSrvsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_MODESRVS_H
