// Generated by gencpp from file uav_client/ModeSrvsResponse.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_MODESRVSRESPONSE_H
#define UAV_CLIENT_MESSAGE_MODESRVSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_client
{
template <class ContainerAllocator>
struct ModeSrvsResponse_
{
  typedef ModeSrvsResponse_<ContainerAllocator> Type;

  ModeSrvsResponse_()
    : feedback(0)  {
    }
  ModeSrvsResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::uav_client::ModeSrvsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_client::ModeSrvsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeSrvsResponse_

typedef ::uav_client::ModeSrvsResponse_<std::allocator<void> > ModeSrvsResponse;

typedef boost::shared_ptr< ::uav_client::ModeSrvsResponse > ModeSrvsResponsePtr;
typedef boost::shared_ptr< ::uav_client::ModeSrvsResponse const> ModeSrvsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_client::ModeSrvsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_client::ModeSrvsResponse_<ContainerAllocator1> & lhs, const ::uav_client::ModeSrvsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_client::ModeSrvsResponse_<ContainerAllocator1> & lhs, const ::uav_client::ModeSrvsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::ModeSrvsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::ModeSrvsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::ModeSrvsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ceb5b32ea3af22073ede4a0328249e";
  }

  static const char* value(const ::uav_client::ModeSrvsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ceb5b32ea3af22ULL;
  static const uint64_t static_value2 = 0x073ede4a0328249eULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_client/ModeSrvsResponse";
  }

  static const char* value(const ::uav_client::ModeSrvsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 feedback\n"
"\n"
;
  }

  static const char* value(const ::uav_client::ModeSrvsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeSrvsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_client::ModeSrvsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_client::ModeSrvsResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_MODESRVSRESPONSE_H
