// Generated by gencpp from file uav_client/MoveMsgs.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_MOVEMSGS_H
#define UAV_CLIENT_MESSAGE_MOVEMSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_client
{
template <class ContainerAllocator>
struct MoveMsgs_
{
  typedef MoveMsgs_<ContainerAllocator> Type;

  MoveMsgs_()
    : mode(0)  {
    }
  MoveMsgs_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::uav_client::MoveMsgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_client::MoveMsgs_<ContainerAllocator> const> ConstPtr;

}; // struct MoveMsgs_

typedef ::uav_client::MoveMsgs_<std::allocator<void> > MoveMsgs;

typedef boost::shared_ptr< ::uav_client::MoveMsgs > MoveMsgsPtr;
typedef boost::shared_ptr< ::uav_client::MoveMsgs const> MoveMsgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_client::MoveMsgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_client::MoveMsgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_client::MoveMsgs_<ContainerAllocator1> & lhs, const ::uav_client::MoveMsgs_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_client::MoveMsgs_<ContainerAllocator1> & lhs, const ::uav_client::MoveMsgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::MoveMsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::MoveMsgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::MoveMsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::MoveMsgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::MoveMsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::MoveMsgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_client::MoveMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff63f6ea3c3e9b7504b2cb3ee0a09d92";
  }

  static const char* value(const ::uav_client::MoveMsgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff63f6ea3c3e9b75ULL;
  static const uint64_t static_value2 = 0x04b2cb3ee0a09d92ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_client::MoveMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_client/MoveMsgs";
  }

  static const char* value(const ::uav_client::MoveMsgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_client::MoveMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
;
  }

  static const char* value(const ::uav_client::MoveMsgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_client::MoveMsgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveMsgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_client::MoveMsgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_client::MoveMsgs_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_MOVEMSGS_H
