// Generated by gencpp from file uav_client/MoveSrvs.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_MOVESRVS_H
#define UAV_CLIENT_MESSAGE_MOVESRVS_H

#include <ros/service_traits.h>


#include <uav_client/MoveSrvsRequest.h>
#include <uav_client/MoveSrvsResponse.h>


namespace uav_client
{

struct MoveSrvs
{

typedef MoveSrvsRequest Request;
typedef MoveSrvsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveSrvs
} // namespace uav_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_client::MoveSrvs > {
  static const char* value()
  {
    return "cecb58d04127b4205e6e2be03ba9e46a";
  }

  static const char* value(const ::uav_client::MoveSrvs&) { return value(); }
};

template<>
struct DataType< ::uav_client::MoveSrvs > {
  static const char* value()
  {
    return "uav_client/MoveSrvs";
  }

  static const char* value(const ::uav_client::MoveSrvs&) { return value(); }
};


// service_traits::MD5Sum< ::uav_client::MoveSrvsRequest> should match
// service_traits::MD5Sum< ::uav_client::MoveSrvs >
template<>
struct MD5Sum< ::uav_client::MoveSrvsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::MoveSrvs >::value();
  }
  static const char* value(const ::uav_client::MoveSrvsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::MoveSrvsRequest> should match
// service_traits::DataType< ::uav_client::MoveSrvs >
template<>
struct DataType< ::uav_client::MoveSrvsRequest>
{
  static const char* value()
  {
    return DataType< ::uav_client::MoveSrvs >::value();
  }
  static const char* value(const ::uav_client::MoveSrvsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_client::MoveSrvsResponse> should match
// service_traits::MD5Sum< ::uav_client::MoveSrvs >
template<>
struct MD5Sum< ::uav_client::MoveSrvsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::MoveSrvs >::value();
  }
  static const char* value(const ::uav_client::MoveSrvsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::MoveSrvsResponse> should match
// service_traits::DataType< ::uav_client::MoveSrvs >
template<>
struct DataType< ::uav_client::MoveSrvsResponse>
{
  static const char* value()
  {
    return DataType< ::uav_client::MoveSrvs >::value();
  }
  static const char* value(const ::uav_client::MoveSrvsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_MOVESRVS_H
