// Generated by gencpp from file uav_client/UavSrvs.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_UAVSRVS_H
#define UAV_CLIENT_MESSAGE_UAVSRVS_H

#include <ros/service_traits.h>


#include <uav_client/UavSrvsRequest.h>
#include <uav_client/UavSrvsResponse.h>


namespace uav_client
{

struct UavSrvs
{

typedef UavSrvsRequest Request;
typedef UavSrvsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UavSrvs
} // namespace uav_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_client::UavSrvs > {
  static const char* value()
  {
    return "cf0091775db056556bcbf0c6e550c71f";
  }

  static const char* value(const ::uav_client::UavSrvs&) { return value(); }
};

template<>
struct DataType< ::uav_client::UavSrvs > {
  static const char* value()
  {
    return "uav_client/UavSrvs";
  }

  static const char* value(const ::uav_client::UavSrvs&) { return value(); }
};


// service_traits::MD5Sum< ::uav_client::UavSrvsRequest> should match
// service_traits::MD5Sum< ::uav_client::UavSrvs >
template<>
struct MD5Sum< ::uav_client::UavSrvsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::UavSrvs >::value();
  }
  static const char* value(const ::uav_client::UavSrvsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::UavSrvsRequest> should match
// service_traits::DataType< ::uav_client::UavSrvs >
template<>
struct DataType< ::uav_client::UavSrvsRequest>
{
  static const char* value()
  {
    return DataType< ::uav_client::UavSrvs >::value();
  }
  static const char* value(const ::uav_client::UavSrvsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_client::UavSrvsResponse> should match
// service_traits::MD5Sum< ::uav_client::UavSrvs >
template<>
struct MD5Sum< ::uav_client::UavSrvsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_client::UavSrvs >::value();
  }
  static const char* value(const ::uav_client::UavSrvsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_client::UavSrvsResponse> should match
// service_traits::DataType< ::uav_client::UavSrvs >
template<>
struct DataType< ::uav_client::UavSrvsResponse>
{
  static const char* value()
  {
    return DataType< ::uav_client::UavSrvs >::value();
  }
  static const char* value(const ::uav_client::UavSrvsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_UAVSRVS_H
