// Generated by gencpp from file uav_client/UavSrvsResponse.msg
// DO NOT EDIT!


#ifndef UAV_CLIENT_MESSAGE_UAVSRVSRESPONSE_H
#define UAV_CLIENT_MESSAGE_UAVSRVSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_client
{
template <class ContainerAllocator>
struct UavSrvsResponse_
{
  typedef UavSrvsResponse_<ContainerAllocator> Type;

  UavSrvsResponse_()
    : feedback(0)  {
    }
  UavSrvsResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::uav_client::UavSrvsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_client::UavSrvsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UavSrvsResponse_

typedef ::uav_client::UavSrvsResponse_<std::allocator<void> > UavSrvsResponse;

typedef boost::shared_ptr< ::uav_client::UavSrvsResponse > UavSrvsResponsePtr;
typedef boost::shared_ptr< ::uav_client::UavSrvsResponse const> UavSrvsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_client::UavSrvsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_client::UavSrvsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_client::UavSrvsResponse_<ContainerAllocator1> & lhs, const ::uav_client::UavSrvsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_client::UavSrvsResponse_<ContainerAllocator1> & lhs, const ::uav_client::UavSrvsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_client::UavSrvsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_client::UavSrvsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_client::UavSrvsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c99621d1dee505388e972db86733bb8";
  }

  static const char* value(const ::uav_client::UavSrvsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c99621d1dee5053ULL;
  static const uint64_t static_value2 = 0x88e972db86733bb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_client/UavSrvsResponse";
  }

  static const char* value(const ::uav_client::UavSrvsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 feedback\n"
"\n"
;
  }

  static const char* value(const ::uav_client::UavSrvsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UavSrvsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_client::UavSrvsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_client::UavSrvsResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CLIENT_MESSAGE_UAVSRVSRESPONSE_H
